[workspace]
members = [
    "roxy",
    "roxy-cli"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "리버스 프록시 서버와 관리 도구"
resolver = "2"

[profile.test]
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 16
