[proxy]
docker_network = "reverse-proxy-network"
label_prefix = "reverse-proxy."
http_port = 80
https_enabled = false
https_port = 443

[logging]
format = "text"  # "text" 또는 "json"
level = "info"   # "error", "warn", "info", "debug", "trace"
output = "stdout"  # "stdout" 또는 파일 경로 