services:
  reverse-proxy:
    build: .
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROXY_DOCKER_NETWORK=reverse-proxy-network
      - PROXY_LABEL_PREFIX=reverse-proxy.
      - PROXY_HTTP_PORT=80
    restart: unless-stopped
    user: root
    networks:
      - reverse-proxy-network

  # 테스트용 백엔드 서비스들
  web1:
    image: nginx:alpine
    container_name: web1
    expose:
      - "80"
    labels:
      - "reverse-proxy.host=test.localhost"
      - "reverse-proxy.port=80"
    networks:
      - reverse-proxy-network
    volumes:
      - ./test/web1:/usr/share/nginx/html

  web2:
    image: nginx:alpine
    container_name: web2
    expose:
      - "80"
    labels:
      - "reverse-proxy.host=test.localhost"
      - "reverse-proxy.port=80"
    networks:
      - reverse-proxy-network
    volumes:
      - ./test/web2:/usr/share/nginx/html

# 테스트를 위한 네트워크 설정
networks:
  reverse-proxy-network:
    name: reverse-proxy-network 