services:
  reverse-proxy:
    build: .
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    user: root
    networks:
      - reverse-proxy-network

  # 테스트용 백엔드 서비스들
  web1:
    image: nginx:alpine
    container_name: web1
    expose:
      - "80"
    labels:
      - "reverse-proxy.host=web1.localhost"
      - "reverse-proxy.port=80"
    networks:
      - reverse-proxy-network

  web2:
    image: nginx:alpine
    container_name: web2
    expose:
      - "80"
    labels:
      - "reverse-proxy.host=web2.localhost"
      - "reverse-proxy.port=80"
    networks:
      - reverse-proxy-network

# 테스트를 위한 네트워크 설정
networks:
  reverse-proxy-network:
    name: reverse-proxy-network 